// ── Severity levels ──────────────────────────────────────────
export type Severity = 'critical' | 'warning' | 'info';

// ── Source that originally detected the anomaly ─────────────
export type DetectionSource = 'tavily' | 'yutori' | 'render_health' | 'manual';

// ── Raw signal coming out of a detector ─────────────────────
export interface DetectionSignal {
  source: DetectionSource;
  title: string;
  summary: string;
  url?: string;
  timestamp: string; // ISO-8601
  raw?: unknown;
}

// ── Incident created by the analyzer from one or more signals
export interface Incident {
  id: string;
  title: string;
  summary: string;
  severity: Severity;
  detectedAt: string;
  resolvedAt?: string;
  services: string[];
  errors: string[];
  rootCause?: string;
  signals: DetectionSignal[];
  remediationActions: RemediationAction[];
  postMortem?: PostMortem;
}

// ── A single remediation step taken by the remediator ───────
export interface RemediationAction {
  id: string;
  type: 'restart' | 'scale' | 'alert' | 'noop';
  targetService: string;
  description: string;
  executedAt: string;
  success: boolean;
  details?: string;
}

// ── Post-mortem generated by the reporter ───────────────────
export interface PostMortem {
  incidentId: string;
  title: string;
  timeline: string;
  rootCause: string;
  impact: string;
  remediation: string;
  lessonsLearned: string;
  generatedAt: string;
}

// ── Render service representation ───────────────────────────
export interface RenderService {
  id: string;
  name: string;
  type: string;
  status: string;
  url?: string;
}

// ── Activity log entry for dashboard ────────────────────────
export interface ActivityLogEntry {
  timestamp: string;
  agent: 'detector' | 'analyzer' | 'remediator' | 'reporter' | 'system';
  message: string;
  data?: unknown;
}

// ── Neo4j graph stats for dashboard ─────────────────────────
export interface GraphStats {
  incidents: number;
  services: number;
  errors: number;
  rootCauses: number;
  remediations: number;
  postMortems: number;
}

// ── Yutori scout config ─────────────────────────────────────
export interface ScoutConfig {
  name: string;
  urls: string[];
  keywords: string[];
  interval?: number; // minutes
}

export interface ScoutUpdate {
  scoutId: string;
  title: string;
  summary: string;
  url?: string;
  detectedAt: string;
}
